name: pageturner_app
description: A Flutter companion app for KoReader PageTurner plugin
version: 1.2.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  vibration: ^3.1.5
  udp: ^5.0.3
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.14.4
  wakelock_plus: ^1.4.0
  screen_brightness: ^2.1.7
  http: ^1.1.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/